
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <div class="listing-wrap" id="products-list">
        

    <?php foreach ($_productCollection as $_product): ?>
        <div class="listingrow w-row item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
<div class="listingcol1 w-col w-col-2 w-col-stack"></div>

<div class="listingcol2 w-col w-col-5 w-col-stack"><div class="listingcol2paddingdiv"><div class="itemdetinfotext listinginfo"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?><br><span class="itemdetbigandbold"><?php echo ($currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol()); echo number_format($_product->getPrice(), 2, '.', '') ?></span>&nbsp; &nbsp;EA &nbsp; &nbsp; Lead Time: <span class="itemdetbold">14 days</span></div><div class="addtocartwrap listing"><div class="quantitytext">Quantity:</div><div class="quantityform"><div class="quantitynumber">1</div></div>


        <div class="addtocartbutton" style="float: right;margin-top: 15px;">
            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
            <div class="addtocarttext" style="cursor: pointer;" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></div>
            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
            <div class="addtocarttext"><?php echo $this->quoteEscape($this->__('View Details')) ?></div>
            <?php else: ?>
            <div class="addtocarttext"><?php echo $this->__('Out of stock') ?></div>
            <?php endif; ?>
        </div>


    <div class="addtomylists">
        <?php if ($this->helper('wishlist')->isAllow()) : ?>
            <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to My Lists') ?></a>
        <?php endif; ?>
    </div>



</div></div></div>

<div class="listingcol3 w-col w-col-5 w-col-stack"><div class="height itemdetinfotext listinginfo">Model Type:&nbsp;Normal <br>AnatomyMaterial:&nbsp;Solid White Plastic<br>Size:&nbsp;Medium<br>Color:&nbsp;White<br>Orientation:&nbsp;N/A<br><br><span class="itemdetailtextsmall"><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a></span></div></div>


            
        </div>
    <?php endforeach; ?>
    </div>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>


    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <ul class="products-grid products-grid--max-<?php echo $_columnCount; ?>-col">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
            
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a>
                <div class="product-info">
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                    <?php
                    if ($this->getChild('name.after')) {
                        $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                        foreach ($_nameAfterChildren as $_nameAfterChildName) {
                            $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                            $_nameAfterChild->setProduct($_product);
                            echo $_nameAfterChild->toHtml();
                        }
                    }
                    ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                    <div class="actions">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
<?php

if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
