<!DOCTYPE html>
<html>
<head>
	<title>Sawbones - Product Homepage</title>
	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/sawbones-product-homepage.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/quangtran.css" type="text/css" />
	<link rel="stylesheet" href="<?php echo $this->getSkinUrl(); ?>css/font-awesome.min.css" type="text/css" />
	<script src="https://ajax.googleapis.com/ajax/libs/webfont/1.4.7/webfont.js"></script>
	<script type="text/javascript">WebFont.load({
  google: {
    families: ["Lato:100,100italic,300,300italic,400,400italic,700,700italic,900,900italic"]
  }
});</script>
</head>
<body class="body">
    <?php echo $this->getChildHtml('header') ?>

    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/home.phtml')->toHtml(); ?>

</div>
<?php echo $this->getChildHtml('footer') ?>

</body>

</html>