<div class="section-header">
	<div class="navbar w-nav">
		<div class="nav-container w-container">
		    <a class="brandwrap w-clearfix w-nav-brand" href="#"><img class="sawboneslogo" src="http://uploads.webflow.com/57994ac141136a134b02557d/57a600cec3e841c509ebf7a2_sawbones-logo-white.png" width="215">
		    </a>
		    <nav class="nav-menu w-nav-menu" role="navigation">
		    	<!-- <a class="active nav-link w-nav-link" href="#" style="max-width: 940px;">Products&nbsp;<span class="fa-blue"></span></a>
		    	<a class="nav-link w-nav-link" href="#" style="max-width: 940px;">Materials &amp; Use Guide&nbsp;<span class="fa-blue"></span></a>
		    	<a class="nav-link w-nav-link" href="#" style="max-width: 940px;">Custom Models&nbsp;<span class="fa-blue"></span></a> -->
		    	 <?php echo $this->getChildHtml('topMenu') ?>
		    </nav>
		    <div class="menubutton w-nav-button">
		        <div class="icon w-icon-nav-menu"></div>
		    </div>
		</div>

		<div class="search">
			<h3 class="searchicon"> Enter keyword or item #</h3>
		</div>
		<div class="w-nav-overlay"></div>
	</div>
</div>