
    <h2 class="h2 product-detail">Pelvis-Full</h2>
    <div class="categorylink">Orthopaedic Models</div>
    <h3 class="narrowby">Narrow By:</h3>
    <div class="categorywrap">
        <div class="categoryblock w-clearfix">
            <h4 class="categoryblocktext">Color</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock w-clearfix">
            <h4 class="categoryblocktext">Material</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock w-clearfix">
            <h4 class="categoryblocktext">Model Type</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock w-clearfix">
            <h4 class="categoryblocktext">Orientation</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock w-clearfix">
            <h4 class="categoryblocktext">Color</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
    </div>
