
    <h3 class="narrowby">Narrow By:</h3>
    <div class="categorywrap">
        <div class="categoryblock">
            <h4 class="categoryblocktext">Composite Bones</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock">
            <h4 class="categoryblocktext">Composite Bones</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock">
            <h4 class="categoryblocktext">Composite Bones</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
        <div class="categoryblock">
            <h4 class="categoryblocktext">Composite Bones</h4>
            <h4 class="categoryblocktext farrow"></h4>
        </div>
	</div>
<!-- 
		<?php 
	$category = Mage::getModel('catalog/category')->load(4);
	$subcategories = $category->getChildrenCategories();
	if (count($subcategories) > 0){
	   echo $category->getName();
	    foreach($subcategories as $subcategory){ ?>
			<div class="categoryblock">
	            <a href="<?php   echo $subcategory->getURL(); ?>"><h4 class="categoryblocktext"><?php echo $subcategory->getName(); ?></h4></a>
	            <h4 class="categoryblocktext farrow"></h4>
	        </div>
	<?php } } ?> -->